name: Build and Deploy
env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically set by Github Actions
  USE_GITHUB_DATA: "true"
  MEDIUM_USERNAME: "Mahitha-Work" # Change this to your medium username
on:
  workflow_dispatch:
  push: 
    branches: feature
    
   # see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3 # If you're using actions/checkout@v3 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
                   sudo mkdir -p /var/www/sample-frontend
      - name: Copy Frontend
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./frontend/platforms/web/dist/*"
          target: "/var/www/vivn-frontend"
          strip_components: 4
            

      

      - name: Install and Build 🔧 # Build the Project
        run: |
          npm install --legacy-peer-deps
          npm run build
    
         
      
